# Terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -sg escape-time 10

# General
set -g base-index 1
set -g pane-base-index 1
set -g mouse on

# Prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Bindings
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind S command-prompt -p "session name:" "new-session -s '%%'"
bind q killw
bind x killp